export const STATE_CODES: Record<string, string> = {
  AN: "Andaman and Nicobar Islands",
  AP: "Andhra Pradesh",
  AR: "Arunachal Pradesh",
  AS: "Assam",
  BR: "Bihar",
  CH: "Chandigarh",
  CG: "Chhattisgarh",
  DD: "Dadra and Nagar Haveli and Daman and Diu",
  DL: "Delhi",
  GA: "Goa",
  GJ: "Gujarat",
  HR: "Haryana",
  HP: "Himachal Pradesh",
  JK: "Jammu and Kashmir",
  JH: "Jharkhand",
  KA: "Karnataka",
  KL: "Kerala",
  LA: "Ladakh",
  LD: "Lakshadweep",
  MP: "Madhya Pradesh",
  MH: "Maharashtra",
  MN: "Manitoba",
  ML: "Meghalaya",
  MZ: "Mizoram",
  NL: "Nagaland",
  OD: "Odisha",
  PY: "Puducherry",
  PB: "Punjab",
  RJ: "Rajasthan",
  SK: "Sikkim",
  TN: "Tamil Nadu",
  TS: "Telangana",
  TR: "Tripura",
  UP: "Uttar Pradesh",
  UK: "Uttarakhand",
  WB: "West Bengal",
};

export const RTO_ZONES: Record<string, string> = {
  "KA01": "Koramangala, Bangalore Central",
  "KA02": "Rajajinagar, Bangalore West",
  "KA03": "Indiranagar, Bangalore East",
  "KA04": "Yeshwanthpur, Bangalore North",
  "KA05": "Jayanagar, Bangalore South",
  "KA51": "Electronic City, Bangalore",
  "KA53": "KR Puram, Bangalore",
  "MH01": "Mumbai Central",
  "MH02": "Mumbai West",
  "MH03": "Mumbai East",
  "MH12": "Pune",
  "DL01": "North Delhi",
  "DL02": "North West Delhi",
  "DL03": "South Delhi",
  "TN01": "Chennai Central",
  "UP16": "Noida",
  "UP14": "Ghaziabad",
  "TS09": "Hyderabad Central",
  "WB01": "Kolkata Beltala",
};
